In [ ]:
from sklearn import preprocessing
import pandas as pd
from seaborn import load_dataset
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler
import numpy as np

## Carregar a base TITANIC do seaborn

In [ ]:
df = load_dataset('titanic')

## Observar a quantidade de NaN existente no atributo "deck"

In [ ]:
df['deck'].isna().sum()

688

## Remover as linhas que tenham valores NaN

In [ ]:
df.dropna(inplace = True)
df.drop(['deck'], axis = 1,inplace = True)

In [ ]:
label_encoder = preprocessing.LabelEncoder()
df['class'] = label_encoder.fit_transform(df['class'])
df['class'] = df['class'] + 1

In [ ]:
df.info()

## Observar a relação dos atributos "pclass" com "class"

In [ ]:
r2 = r2_score(df['pclass'], df['class'])
print('r2 score for perfect model is', r2)

r2 score for perfect model is 1.0

## Transformar todos os atributos categóricos usando One-Hot Encoder

## Coluna target é a "pclass" ou "survived"

In [ ]:
y = df['survived']
df.drop(['survived'], axis = 1,inplace = True)

column_transformer = make_column_transformer((OneHotEncoder(), ['alone','alive','embark_town','adult_male','embarked', 'sex', 'who']), remainder='passthrough')
df = column_transformer.fit_transform(df)
df = pd.DataFrame(data=df, columns = column_transformer.get_feature_names_out())

X = df
df

,onehotencoder__alone_False,onehotencoder__alone_True,onehotencoder__alive_no,onehotencoder__alive_yes,onehotencoder__embark_town_Cherbourg,onehotencoder__embark_town_Queenstown,onehotencoder__embark_town_Southampton,onehotencoder__adult_male_False,onehotencoder__adult_male_True,onehotencoder__embarked_C,...,onehotencoder__sex_male,onehotencoder__who_child,onehotencoder__who_man,onehotencoder__who_woman,remainder__pclass,remainder__age,remainder__sibsp,remainder__parch,remainder__fare,remainder__class
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,38.0,1.0,0.0,71.2833,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,35.0,1.0,0.0,53.1000,1.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,54.0,0.0,0.0,51.8625,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,3.0,4.0,1.0,1.0,16.7000,3.0
4,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,58.0,0.0,0.0,26.5500,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,47.0,1.0,1.0,52.5542,1.0
178,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,33.0,0.0,0.0,5.0000,1.0
179,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,56.0,0.0,1.0,83.1583,1.0
180,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,19.0,0.0,0.0,30.0000,1.0
181,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,30.0000,1.0

## Separar os dados de treinamento e testes

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=None, stratify = y)

## Treinar 2 árvores de decisão com características diferentes

In [ ]:
def printTreino(model):
  result = model.predict(X_test)
  acc = metrics.accuracy_score(result, y_test)
  show = round(acc * 100)
  print("{}%".format(show))

In [ ]:
model1 = DecisionTreeClassifier(criterion="entropy")
model1.fit(X_train, y_train)

printTreino(model1)

100%

In [ ]:
model2 = DecisionTreeClassifier(max_depth=2)
model2.fit(X_train, y_train)

printTreino(model2)

100%

## Treinar 2 kNN com características diferentes

In [ ]:
model3 = KNeighborsClassifier(n_neighbors=7, metric='euclidean', algorithm='brute')
model3.fit(X_train, y_train)

printTreino(model3)

73%

In [ ]:
model4 = KNeighborsClassifier(n_neighbors=7, algorithm='brute')
model4.fit(X_train, y_train)

printTreino(model4)

73%

## Carregar a base TRANSFUSION. URL da base segue abaixo:

In [ ]:
url = "https://raw.githubusercontent.com/tmoura/machinelearning/master/transfusion.data"

## A coluna 0 (zero) é o TARGET.

In [ ]:
dataset = pd.read_csv(url, header=None)
dataset

     0   1   2      3   4
0    1   2  50  12500  98
1    1   0  13   3250  28
2    1   1  16   4000  35
3    1   2  20   5000  45
4    2   1  24   6000  77
..  ..  ..  ..    ...  ..
743  2  23   2    500  38
744  2  21   2    500  52
745  2  23   3    750  62
746  2  39   1    250  39
747  2  72   1    250  72

[748 rows x 5 columns]

## Observe que a magnitude dos atributos é bem diferente, então cada atributo deve ser normalizado (código no mini tutorial de pandas).

In [ ]:
for i in range (len(dataset.columns)):
  dataset[i] = MinMaxScaler().fit_transform(np.array(dataset[i]).reshape(-1,1))

In [ ]:
columns = len(dataset.columns)

y = dataset[0] # extrai a primeira coluna, que é o label
X = dataset.loc[:,1:columns-1]

## Separar os dados de treinamento e testes

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=None, stratify=y) # 80% treino e 20% teste

## Treinar 2 árvores de decisão com características diferentes

In [ ]:
model5 = DecisionTreeClassifier(criterion="entropy")
model5.fit(X_train, y_train)

printTreino(model5)

67%

In [ ]:
model6 = DecisionTreeClassifier(max_depth=2)
model6.fit(X_train, y_train)

printTreino(model6)

76%

## Treinar 2 kNN com características diferentes

In [ ]:
model7 = KNeighborsClassifier(n_neighbors=7, metric='euclidean', algorithm='brute')
model7.fit(X_train, y_train)

printTreino(model7)

77%

In [ ]:
model8 = KNeighborsClassifier(n_neighbors=7, algorithm='brute')
model8.fit(X_train, y_train)

printTreino(model8)

77%